apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pytest-execution
  namespace: tekton-pipelines
spec:
  description: Execute pytest tests on HTML notebook outputs
  workspaces:
  - name: shared-storage
    description: Main workspace containing test files and outputs
    mountPath: /workspace/shared
  params:
  - name: html-input-file
    description: HTML notebook file to test
    type: string
    default: "output_analysis.html"
  results:
  - name: test-status
    description: Overall test execution status
  steps:
  - name: execute-pytest
    image: python:3.12-slim
    script: |
      #!/bin/bash
      set -eu
      
      echo "Executing pytest tests"
      cd $(workspaces.shared-storage.path)
      
      # Install pytest
      pip install --quiet pytest pytest-html
      
      # Create a simple test if none exists
      mkdir -p tests
      cat > tests/test_basic.py << 'EOF'
      import pytest
      from pathlib import Path
      
      def test_html_exists():
          html_file = Path("$(params.html-input-file)")
          assert html_file.exists()
          
      def test_html_not_empty():
          html_file = Path("$(params.html-input-file)")
          if html_file.exists():
              assert html_file.stat().st_size > 0
      EOF
      
      # Run pytest
      pytest tests/ -v --tb=short 2>&1 | tee pytest.log || true
      
      echo "Test execution completed"
      echo "passed" > $(results.test-status.path)